name: Generate GitHub Stats SVGs

on:
  schedule:
    - cron: '0 */12 * * *' # Runs every 12 hours
  workflow_dispatch: # Allows you to run it manually right away

jobs:
  generate-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Fetch Stats Cards
        run: |
          # Download your general stats layout
          curl -s "https://github-stats-extended.vercel.app/api?username=nikhilchowdary26&show_icons=true&theme=radical&include_all_commits=true&count_private=true" > github-stats.svg
          
          # Download your top coding languages layout
          curl -s "https://github-stats-extended.vercel.app/api/top-langs/?username=nikhilchowdary26&layout=compact&theme=radical&langs_count=7" > github-langs.svg

      - name: Commit and Push Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add github-stats.svg github-langs.svg
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update profile metrics SVGs" && git push)